  COOP#    atomMU    atomNU   distance   translation   ICOOP (at) eF 
                                                          for spin 1 
      1        C1        C2    1.54578     0  -1   0         0.40910 
      2        C1        C2    1.54578     1  -1   0         0.40910 
      3        C1        C2    1.54578     0   0   0         0.40910 
      4        C1        C2    1.54578     0  -1   1         0.40910 