Atomic and orbital valences (IDOV)

  atom#    atom  basisfunction        Valence
                                   For spin 1
      1       C             2s           0.99 
                          2p_y           0.99 
                          2p_z           0.99 
                          2p_x           0.99 
                         total           3.95 
      2       C             2s           0.99 
                          2p_y           0.99 
                          2p_z           0.99 
                          2p_x           0.99 
                         total           3.95 