  COHP#    atomMU    atomNU   distance   translation   ICOHP (at) eF 
                                                          for spin 1 
      1        C1        C2    1.54578     0  -1   0        -9.60394 
      2        C1        C2    1.54578     1  -1   0        -9.60394 
      3        C1        C2    1.54578     0   0   0        -9.60394 
      4        C1        C2    1.54578     0  -1   1        -9.60394 