  COBI#    atomMU    atomNU   distance   translation   ICOBI (at) eF 
                                                          for spin 1 
      1        C1        C2    1.54578     0  -1   0         0.95028 
      2        C1        C2    1.54578     1  -1   0         0.95028 
      3        C1        C2    1.54578     0   0   0         0.95028 
      4        C1        C2    1.54578     0  -1   1         0.95028 